# 워크플로우의 제목
name: Gatsby Publish

on:
  # pull request가 생성되었을 때 실행됩니다.
  pull_request:
    branches:
      - master  # 'master' 브랜치에 대한 pull request

  # push되었을 때 실행됩니다.
  push:
    branches:
      - master  # 'master' 브랜치에 대한 push

jobs:
  # 배포 작업 정의
  deploy:
    runs-on: ubuntu-latest  # 최신 Ubuntu 환경에서 실행
    steps:
      - uses: actions/checkout@v4 # 코드 리포지토리를 체크아웃합니다.
      - uses: enriikke/gatsby-gh-pages-action@v2  
        with:
          access-token: ${{ secrets.HDLOG_KEY }}  # GitHub Secrets에 저장된 액세스 토큰을 사용하여 배포합니다.
          deploy-branch: deploy/DEV  # 배포할 브랜치를 'deploy/DEV'로 설정합니다.
          skip-publish: false  # 배포를 건너뛰지 않도록 설정합니다.
